# Generated by Django 3.2.10 on 2021-12-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('transcription', models.TextField()),
                ('translations', models.TextField()),
                ('examples', models.TextField()),
                ('show_count', models.IntegerField()),
            ],
        ),
    ]
