# Generated by Django 3.2.10 on 2022-01-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocapp', '0006_rename_book_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphs',
            name='id_book',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Идентификатор книги'),
        ),
    ]
